=== dbdb5269/Corejava/src/XML/homework/three/DTDtest.dtd
<!--外部DTD-->

<!--属性类型
    1.CDATA：任意字符（包括数字和中文）
    2.ID：唯一 不能以数字开头 在同一个XML是唯一的
    3.IDREF:只允许指向一个存在的ID
    IDREFS:允许指向多个存在的ID
    4.（枚举1／枚举2/枚举3）:属性只允许是枚举值
    属性特点
    #REQUIRED 必须出现
    #IMPLIED 非必须
    default-value :默认值 可以不出现 不出现的话是默认值 如果出现设置的值是什么就是什么
    #FIXED：可以不出现 如果出现则必须是默认值




    -->
<!ELEMENT students (student+)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT street (#PCDATA)>
<!ELEMENT zip (#PCDATA)>
<!ELEMENT address (city,street,zip)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT first_name (#PCDATA)>
<!ELEMENT last_name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT gendar (#PCDATA)>
<!ELEMENT student (first_name,last_name,age,gendar,address)>

=== dbdb5269/Corejava/src/XML/dtdtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--约束元素 element-->
<!--内部DTD-->
<!--书写实体entity和DTD的位置-->
<!DOCTYPE students SYSTEM "XML/DTDtest.dtd">
<students>
    <student id="and2013001" pid="and2013002" gender="男" nativeplace="山西">
        <name></name>
        <address></address>
    </student>
    <student id="and2013002" pid="and2013003" gender="女">
        <name></name>
        <address></address>
    </student>
    <student id="and2013003" pid="and2013001" gender="女">
        <name></name>
        <address></address>
    </student>
</students>

=== dbdb5269/Corejava/src/XML/homework/three/students.xml
<?xml version="1.0" encoding="utf-8" ?>

<!DOCTYPE students SYSTEM "DTDtest.dtd">

<students>
    <student>
        <first_name></first_name>
        <last_name></last_name>
        <age></age>
        <gendar></gendar>
        <address>
            <city></city>
            <street></street>
            <zip></zip>
        </address>
    </student>
</students>
